const templateTasks = [
  {   title: "Review quarterly budget",
      time: "30 mins",
      description: "We need to go over how much money we are going to spend between projects and finalize with the management team. Last quarter the team ran over budget so it is important to be disciplined this quarter.",
      isDone: false,
  },
  {   title: "Travel Planning",
      time: "20 mins",
      description: "Plan logistics of upcoming company retreat to Big Bear. Go over meal planning, expenses, entertainment, etc.",
      isDone: false,
  },
  {   title: "Conference call with Marketing",
      time: "60 mins",
      description: "Call with the marketing team about possible new clients and advertising creative.",
      isDone: false,
  },
  {   title: "Introduce New Team Members",
      time: "20 mins",
      description: "Breif introduction of James and Sarah, the newest additions to our company. Talk about their background and previous experience. Also discuss their roles and give them an opportunity to share information about themselves.",
      isDone: false,
  },
  {   title: "Lunch Break",
      time: "30 mins",
      description: "Lunch is catered from Lemonade. Make sure reception knows to let them in the building and that we have enough plates and utinsels.",
      isDone: false,
  },
];

export default templateTasks;